### ISSUE TITLE
Add docker-compose.yml example file on your proyect.

### ISSUE THREAD

**Issue by demostenes1509** [AndreySenov/firebase-tools-docker#13]
firebaset:
    container_name: firebase
    image: andreysenov/firebase-tools
    user: node
    # command: firebase emulators:start
    command: tail -f /dev/null
    ports:
      - 9005:9005
      - 9099:9099
      - 9199:9199
      - 5001:5001
      - 5000:5000
      - 8080:8080
      - 8085:8085
      - 9000:9000
      - 3003:3003
    volumes:
      - irebase-volume:/home/node

In order to configure it, user should:

- Enter to image and run:

1. firebase login
2. firebase init
3. Modify firebase.json
4. Comment tail command and uncomment firebase emulators:start command

My congrats to your work

**Comment by Skiba-Tomasz** [comment]
Thank you. This was helpful for me.
Could you explain why container exits if I do not provide
command: tail -f /dev/null
in docker-compose?

**Comment by wf9a5m75** [comment]
Thanks @demostenes1509 !

Follow him up:

1. create a `docker-compose.yml` file.
```xml
version: '3'
services:
  app:
    container_name: firebase
    image: andreysenov/firebase-tools
    user: node
    #command: firebase emulators:start
    command: tail -f /dev/null
    ports:
      - 4000:4000
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 8085:8085
      - 9000:9000
      - 9005:9005
      - 9099:9099
      - 9199:9199
    volumes:
      - ./app_dir:/home/node
volumes:
  app_dir:

```

2. then run `docker compose up`.
3. The emulator should start (access to `http://localhost:4000`)

----

> Could you explain why container exits if I do not provide
> command: tail -f /dev/null
> in docker-compose?

If so, the docker exits the container.
To prevent exiting the image, he just specify `tail -f /dev/null`.
If you want to see the emulator outputs, use `firebase emulators:start`.

> please note that in order to setup firebase user has to be set to root

Yes, `root` user is necessary, and it specified in your `Dockerfile`.
`user: node` is running user.

**Comment by wf9a5m75** [comment]
To authenticate firebase, open another terminal window, then

```
$ docker exec -it firebase
(image id):~$ firebase login
Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=...
```

Copy the above URL, and open on your browser, and authenticate the firebase.

After that, the firebase tools recognize successful automatically.

**Comment by wf9a5m75** [comment]
Extra following up.
Someone who wants to run `npm run build:watch`, you can do like this:

**functions/package.json**
```json
{
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch --preserveWatchOutput",
    "serve": "npm run build:watch | firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^10.2.0",
    "firebase-functions": "^3.21.0"
  },
  "devDependencies": {
    "typescript": "^4.6.4"
  },
  "private": true
}
```

**docker-compose.yml**
```yml
version: '3'
services:
  app:
    container_name: firebase
    image: andreysenov/firebase-tools
    user: node
    command: npm run serve --prefix /home/node/functions
    ports:
      - 4000:4000
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 8085:8085
      - 9000:9000
      - 9005:9005
      - 9099:9099
      - 9199:9199
    volumes:
      - ./app_dir:/home/node
volumes:
  app_dir:
```

**Comment by nstanard** [comment]
Hello 👋 I have a docker-compose file very similar to the one described in this thread and I'm trying to run it in a github action. I am running into an error that I can't seem to figure out though.

```
name: Go package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start Firebase
        run: docker-compose -f test/docker-compose.yml run firebase
```

```
Creating network "test_test-net" with driver "bridge"
Creating volume "test_go-mod" with default driver
Creating volume "test_go-build" with default driver
Pulling firebase (andreysenov/firebase-tools:11.13.0)...
11.13.0: Pulling from andreysenov/firebase-tools
Digest: sha256:e7f39d6d36160be27f102eac12b8a12aef0ca7cb779bd78319d1f113293fa234
Status: Downloaded newer image for andreysenov/firebase-tools:11.13.0
Creating test_firebase_run ... 
Creating test_firebase_run ... done
┌────────────────────────────────────────────────────────┐
│           firebase-tools update check failed           │
│          Try running with sudo or get access           │
│          to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/node/.config │
└────────────────────────────────────────────────────────┘
/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:68
			throw error;
			^

Error: EACCES: permission denied, mkdir '/home/node/.config/configstore'
You don't have access to this file.

    at Object.mkdirSync (node:fs:1386:3)
    at AsyncFunction.module.exports.sync (/usr/local/share/.config/yarn/global/node_modules/make-dir/index.js:1[14](https://github.com/theroutingcompany/usermanager/actions/runs/3895231000/jobs/6650282334#step:4:15):6)
    at Configstore.set all [as all] (/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:59:12)
    at Configstore.set (/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:91:12)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/track.js:20:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[18](https://github.com/theroutingcompany/usermanager/actions/runs/3895231000/jobs/6650282334#step:4:19)0:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:[19](https://github.com/theroutingcompany/usermanager/actions/runs/3895231000/jobs/6650282334#step:4:20)) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/node/.config/configstore'
}
1
Error: Process completed with exit code 1.
```

Any ideas/suggestions?

**Comment by giladv** [comment]
@nstanard still getting the same issue even after setting user: node

**Comment by nstanard** [comment]
> @nstanard still getting the same issue even after setting user: node

Oops, sorry. I meant to type "user: root". I updated my comment.

**Comment by giladv** [comment]
@nstanard thanks! trying right now
