### ISSUE TITLE
Not able to run database emulator because Java unavailable

### ISSUE THREAD

**Issue by wouterlemcke** [AndreySenov/firebase-tools-docker#2]
I would like to use this image to run the firebase database emulator.

However this crashes because Java is not available. Can you add support for this?

`Error: database: emulator has exited because java is not installed, you can install it from https://openjdk.java.net/install/`

**Comment by AndreySenov** [comment]
OpenJDK 11 has been added to the image. Please check the `latest` tag.

**Comment by wouterlemcke** [comment]
Thanks for your quick actions!
When starting the database emulator it errors on permission issues. Did you try to run it?

```
┌────────────────────────────────────────────────────────┐
│           firebase-tools update check failed           │
│          Try running with sudo or get access           │
│          to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/node/.config │
└────────────────────────────────────────────────────────┘
/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/home/node/.config/configstore/firebase-tools.json'
You don't have access to this file.

    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Configstore.get (/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:34:26)
    at new Configstore (/usr/local/share/.config/yarn/global/node_modules/configstore/index.js:27:45)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/configstore.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/node/.config/configstore/firebase-tools.json'
}
```

**Comment by ygorduraes** [comment]
I'm also getting this permission issue today. Not related to Java, though.

**Comment by ygorduraes** [comment]
FYI: using an older tag (7.10.0) works for me.

**Comment by AndreySenov** [comment]
Thank you. I've reproduced the issue with EACCES error. Should be fine now in the `latest` tag.

**Comment by ygorduraes** [comment]
Thanks! It works now.

**Comment by akauppi** [comment]
Can this be closed?
